- data/init/guhd
- server/guhcore.cpp
- server/guhcore.h
- server/guhservice.cpp
- server/guhservice.h
- server/main.cpp
- server/qtservice/QtServiceBase
- server/qtservice/QtServiceController
- server/qtservice/qtservice.cpp
- server/qtservice/qtservice.h
- server/qtservice/qtservice.pri
- server/qtservice/qtservice_p.h
- server/qtservice/qtservice_unix.cpp
- server/qtservice/qtservice_win.cpp
- server/qtservice/qtunixserversocket.cpp
- server/qtservice/qtunixserversocket.h
- server/qtservice/qtunixsocket.cpp
- server/qtservice/qtunixsocket.h
- server/server.pro
- server/tcpserver.cpp
- server/tcpserver.h
- tests/auto/checklicenseheaders.sh
the init script still needs 100% cpu on the raspberry...still searching the bug
> added daemon option and application parameters

- debian/control
> Revert "added guh-webserver to guh meta package"

- debian/guh-plugins.install
- libguh/hardware/radio433/radio433.cpp
- libguh/hardware/radio433/radio433.h
- libguh/hardware/radio433/radio433brennenstuhlgateway.cpp
- libguh/hardware/radio433/radio433brennenstuhlgateway.h
- libguh/hardware/radio433/radio433transmitter.cpp
- libguh/hardware/radio433/radio433transmitter.h
- libguh/plugin/deviceplugin.cpp
- libguh/plugin/deviceplugin.h
- plugins/deviceplugins/deviceplugins.pro
- plugins/deviceplugins/leynew/devicepluginleynew.cpp
- plugins/deviceplugins/leynew/devicepluginleynew.h
- plugins/deviceplugins/leynew/devicepluginleynew.json
- plugins/deviceplugins/leynew/leynew.pro
Support for leynew RGB Led controller (433 MHz)
> Leynew plugin

- plugins/deviceplugins/intertechno/devicepluginintertechno.cpp
> fix intertechno plugin

- data/init/guhd
- debian/guhd.postinst
this script will restart guhd after an update, if the service is running, otherwise this script will do nothing.
> added guhd.postinst 

- libguh/types/action.cpp
- libguh/types/event.cpp
- libguh/types/statedescriptor.cpp
- plugins/deviceplugins/leynew/devicepluginleynew.cpp
- plugins/deviceplugins/unitec/devicepluginunitec.cpp
- server/guhcore.cpp
- server/rule.cpp
> fixed documentation warinings

- plugins/deviceplugins/leynew/devicepluginleynew.cpp
fixed brightness and speed steps in leynew plugin
> fixed issue #118

- libguh/plugin/deviceplugin.cpp
- libguh/types/paramtype.cpp
- libguh/types/paramtype.h
- libguh/typeutils.h
- plugins/deviceplugins/commandlauncher/deviceplugincommandlauncher.json
- plugins/deviceplugins/conrad/devicepluginconrad.json
- plugins/deviceplugins/datetime/deviceplugindatetime.json
- plugins/deviceplugins/eq-3/deviceplugineq-3.json
- plugins/deviceplugins/genericelements/deviceplugingenericelements.json
- plugins/deviceplugins/intertechno/devicepluginintertechno.json
- plugins/deviceplugins/leynew/devicepluginleynew.json
- plugins/deviceplugins/lgsmarttv/devicepluginlgsmarttv.json
- plugins/deviceplugins/lircd/devicepluginlircd.json
- plugins/deviceplugins/mailnotification/devicepluginmailnotification.json
- plugins/deviceplugins/openweathermap/devicepluginopenweathermap.json
- plugins/deviceplugins/philipshue/devicepluginphilipshue.json
- plugins/deviceplugins/wakeonlan/devicepluginwakeonlan.json
- plugins/deviceplugins/wemo/devicepluginwemo.json
- plugins/deviceplugins/wifidetector/devicepluginwifidetector.json
- server/jsonrpc/jsonrpcserver.cpp
- server/jsonrpc/jsontypes.cpp
- server/jsonrpc/jsontypes.h
- tests/auto/api.json
add input types to api and updated ParamTypes in deviceplugin json files
> Input types

- server/jsonrpc/jsonrpcserver.cpp
- server/jsonrpc/jsontypes.cpp
- server/jsonrpc/jsontypes.h
- tests/auto/api.json
> added Uint and Color to base types

- libguh/devicemanager.cpp
- libguh/devicemanager.h
- libguh/plugin/deviceplugin.cpp
- libguh/plugin/deviceplugin.h
this method will be called in a deviceplugin once the setup process is finished in the devicemanager
> added postSetupDevice

- debian/changelog
- libguh/libguh.pro
- libguh/types/param.cpp
- libguh/types/ruleaction.cpp
- libguh/types/ruleaction.h
- libguh/types/ruleactionparam.cpp
- libguh/types/ruleactionparam.h
- server/guhcore.cpp
- server/guhcore.h
- server/jsonrpc/jsonrpcserver.cpp
- server/jsonrpc/jsontypes.cpp
- server/jsonrpc/jsontypes.h
- server/jsonrpc/ruleshandler.cpp
- server/jsonrpc/ruleshandler.h
- server/rule.cpp
- server/rule.h
- server/ruleengine.cpp
- server/ruleengine.h
- tests/auto/api.json
- tests/auto/rules/testrules.cpp
added RuleAction and RuleActionParam to RuleEngine
allows to user event params in an ruleaction
> Rule action params

- libguh/devicemanager.cpp
- libguh/devicemanager.h
- server/guhcore.cpp
- server/guhcore.h
- server/jsonrpc/devicehandler.cpp
- server/jsonrpc/devicehandler.h
- server/jsonrpc/jsonrpcserver.cpp
- server/jsonrpc/ruleshandler.cpp
- server/jsonrpc/ruleshandler.h
- server/ruleengine.cpp
- server/ruleengine.h
- tests/auto/api.json
Added notifications for Device Added/Removed and Rule Added/Removed
> Device and rule notifications

- plugins/deviceplugins/openweathermap/devicepluginopenweathermap.cpp
- server/jsonrpc/jsontypes.cpp
> Fix readonly param

- plugins/deviceplugins/lgsmarttv/devicepluginlgsmarttv.cpp
- plugins/deviceplugins/lgsmarttv/devicepluginlgsmarttv.h
- plugins/deviceplugins/lgsmarttv/tvdevice.cpp
fix edit device on LG Smart Tv
> fix Lg Smart Tv

- plugins/deviceplugins/philipshue/devicepluginphilipshue.cpp
- plugins/deviceplugins/philipshue/devicepluginphilipshue.h
change brigtness from 0-255 to 0-100 %
> fix brightness

- guh.pri
- server/guhcore.cpp
- server/guhcore.h
- server/jsonrpc/jsontypes.cpp
- server/jsonrpc/jsontypes.h
- server/jsonrpc/ruleshandler.cpp
- server/jsonrpc/ruleshandler.h
- tests/auto/api.json
- tests/auto/jsonrpc/testjsonrpc.cpp
- tests/auto/rules/testrules.cpp
add rule description type
changed GetRules method
add rule active state to rule details
add RuleActiveChanged notification (and corresponding tests)
> Rule description

- doc/guh.qdoc
- guh.pri
- libguh/plugin/deviceplugin.cpp
- libguh/plugin/deviceplugin.h
- libguh/types/paramtype.cpp
- libguh/types/paramtype.h
- libguh/types/statetype.cpp
- libguh/types/statetype.h
- libguh/typeutils.h
- plugins/deviceplugins/datetime/deviceplugindatetime.json
- plugins/deviceplugins/eq-3/deviceplugineq-3.json
- plugins/deviceplugins/openweathermap/devicepluginopenweathermap.json
- plugins/deviceplugins/philipshue/devicepluginphilipshue.json
- plugins/deviceplugins/tune/deviceplugintune.json
- server/jsonrpc/jsontypes.cpp
- server/jsonrpc/jsontypes.h
- tests/auto/api.json
add units to paramType and StateType
> Param units

- plugins/deviceplugins/tune/deviceplugintune.cpp
- server/guhcore.cpp
> fix rule engine

- plugins/deviceplugins/kodi/jsonhandler.cpp
Player notifications Play, Pause and Stop working now
> fix player notifications

- data/config/guhd.conf
- debian/guhd.install
- libguh/devicemanager.cpp
- libguh/devicemanager.h
- libguh/guhsettings.cpp
- libguh/guhsettings.h
- libguh/hardware/radio433/radio433.cpp
- libguh/libguh.pro
- server/logging/logengine.cpp
- server/main.cpp
- server/ruleengine.cpp
- server/ruleengine.h
- server/stateevaluator.cpp
- server/tcpserver.cpp
- server/tcpserver.h
- tests/auto/devices/testdevices.cpp
- tests/auto/guhtestbase.cpp
- tests/auto/guhtestbase.h
- tests/auto/jsonrpc/testjsonrpc.cpp
added dynamic tcp server
added guhd.conf
> guh settings

- debian/guhd.install
- debian/libguh1-dev.install
- guh.pri
- libguh/libguh.pro
- plugins/generateplugininfo
- plugins/plugins.pri
add generateplugininfo to libguh-dev
> fixed guhd.conf destination

- debian/control
- debian/libguh1-dev.install
- libguh/libguh.pro
- plugins/guh-generateplugininfo
- plugins/plugins.pri
improved generateplugininfo
renamed it
> fixed libguh-dev header files

- libguh/devicemanager.cpp
- plugins/deviceplugins/mock/devicepluginmock.cpp
- plugins/deviceplugins/mock/devicepluginmock.h
- plugins/deviceplugins/mock/devicepluginmock.json
- server/rest/devicesresource.cpp
- tests/auto/devices/testdevices.cpp
- tests/auto/guhtestbase.cpp
- tests/auto/guhtestbase.h
- tests/auto/restdevices/testrestdevices.cpp
Add mock device PushButton
Add mock device DisplayPin
> Add new mock device

- libguh/devicemanager.cpp
> Add missing notifications in devicemanager

- guh.pri
- libguh/devicemanager.cpp
- libguh/devicemanager.h
- libguh/network/upnpdiscovery/upnpdiscoveryrequest.cpp
- libguh/plugin/device.cpp
- libguh/plugin/device.h
- plugins/deviceplugins/philipshue/devicepluginphilipshue.cpp
- plugins/deviceplugins/philipshue/devicepluginphilipshue.json
- server/guhcore.cpp
- server/guhcore.h
- server/jsonrpc/devicehandler.cpp
- server/jsonrpc/jsontypes.cpp
- server/rest/devicesresource.cpp
- server/rest/devicesresource.h
- server/ruleengine.cpp
- tests/auto/api.json
add remove policy to REST
expand remove policy
> Add device parent/child relation

- plugins/deviceplugins/openweathermap/devicepluginopenweathermap.cpp
- plugins/deviceplugins/openweathermap/devicepluginopenweathermap.h
- plugins/deviceplugins/openweathermap/devicepluginopenweathermap.json
small changes in the plugin json
> update openweathermap api changes

- plugins/deviceplugins/mock/devicepluginmock.cpp
- plugins/deviceplugins/mock/devicepluginmock.h
- plugins/deviceplugins/mock/devicepluginmock.json
- tests/auto/devices/testdevices.cpp
- tests/auto/guhtestbase.cpp
- tests/auto/guhtestbase.h
- tests/auto/restdevices/testrestdevices.cpp
> Add display pin mock device

- guh.pri
- libguh/devicemanager.cpp
- libguh/devicemanager.h
- libguh/plugin/deviceplugin.cpp
- libguh/plugin/deviceplugin.h
- plugins/deviceplugins/datetime/deviceplugindatetime.cpp
- plugins/deviceplugins/datetime/deviceplugindatetime.h
- plugins/deviceplugins/eq-3/deviceplugineq-3.cpp
- plugins/deviceplugins/eq-3/deviceplugineq-3.h
- plugins/deviceplugins/mock/devicepluginmock.cpp
- plugins/deviceplugins/mock/devicepluginmock.h
- plugins/deviceplugins/mock/devicepluginmock.json
> fix plugin configuration and move to plugin json file

- debian/guh-plugins.install
- plugins/deviceplugins/awattar/devicepluginawattar.cpp
- plugins/deviceplugins/awattar/heatpump.cpp
- plugins/deviceplugins/deviceplugins.pro
remove autodevice from awattar
> remove osdomotics

- doc/libguh.qdoc
- libguh/coap/coap.cpp
- libguh/coap/coap.h
- libguh/coap/coapobserveresource.cpp
- libguh/coap/coapobserveresource.h
- libguh/coap/coapoption.cpp
- libguh/coap/coappdu.cpp
- libguh/coap/coappdu.h
- libguh/coap/coapreply.cpp
- libguh/coap/coapreply.h
- libguh/coap/corelink.cpp
- libguh/coap/corelinkparser.cpp
- libguh/libguh.pro
> Add CoAP observing resources

- guh.pri
- server/guhapplication.cpp
- tests/auto/jsonrpc/testjsonrpc.cpp
Catch  SIGSEGV and print backtrace to logfile
> Crash logger

- plugins/deviceplugins/awattar/devicepluginawattar.cpp
- plugins/deviceplugins/awattar/heatpump.cpp
- server/guhapplication.cpp
- tests/auto/guhtestbase.cpp
- tests/auto/jsonrpc/testjsonrpc.cpp
- tests/auto/logging/testlogging.cpp
- tests/auto/rules/testrules.cpp
- tests/auto/webserver/testwebserver.cpp
fix some tests to make sure they have enough time to verify
> Fix backtace output + Tests

- plugins/deviceplugins/mock/httpdaemon.cpp
- tests/auto/rules/testrules.cpp
> Recheck rule tests

- guh.pri
- libguh/coap/coappdublock.cpp
- libguh/network/avahi/qtavahiservice.cpp
- libguh/network/avahi/qtavahiservice.h
- libguh/network/avahi/qtavahiservice_p.cpp
- libguh/network/avahi/qtavahiservice_p.h
- libguh/network/avahi/qtavahiservicebrowser_p.cpp
- libguh/network/avahi/qtavahiservicebrowser_p.h
- server/guhconfiguration.cpp
- server/jsonrpc/configurationhandler.cpp
- server/jsonrpc/jsonrpcserver.cpp
- server/rest/restserver.cpp
- server/servermanager.cpp
- server/tcpserver.cpp
- server/webserver.cpp
- server/websocketserver.cpp
- tests/auto/api.json
fixed include file
add missing configuration notifications
> Add avahi service txt entries

- guh.pri
- libguh/devicemanager.cpp
- server/guhapplication.cpp
- server/guhcore.cpp
- server/guhcore.h
- server/jsonrpc/jsontypes.cpp
- server/logging/logengine.cpp
- server/logging/logengine.h
- server/logging/logentry.cpp
- server/logging/logentry.h
- server/logging/logging.h
- server/ruleengine.cpp
- tests/auto/api.json
fix #283
fix #303
small bug fixes and add logging for rule enable/disable and rule action execution
> Update logging engine

- debian/guh-plugins.install
- plugins/deviceplugins/deviceplugins.pro
- plugins/deviceplugins/multisensor/devicepluginmultisensor.cpp
- plugins/deviceplugins/multisensor/devicepluginmultisensor.h
- plugins/deviceplugins/multisensor/devicepluginmultisensor.json
- plugins/deviceplugins/multisensor/multisensor.pro
- plugins/deviceplugins/multisensor/sensortag.cpp
- plugins/deviceplugins/multisensor/sensortag.h
> Multisensor plugin

- server/cloud/cloudauthenticator.cpp
- server/cloud/cloudauthenticator.h
- server/guhconfiguration.cpp
- server/guhconfiguration.h
write initial config file
update cloud authentication server to secure connection (ignoring self signed errors)
> Update configs and cloud auth url

- plugins/deviceplugins/multisensor/sensortag.cpp
> fix multisensor calibration

- doc/test-plugin.qdoc
- doc/write-plugins.qdoc
- libguh/devicemanager.cpp
* more debug output on why a plugin may fail to load
* allow loading plugins without installing them by using the GUH_PLUGINS_PATH env variable
> some improvements for developing plugins

- libguh/devicemanager.cpp
- libguh/devicemanager.h
- server/guhcore.cpp
- server/guhcore.h
- server/jsonrpc/devicehandler.cpp
- server/jsonrpc/devicehandler.h
- tests/auto/jsonrpc/testjsonrpc.cpp
> emit a notification when a plugin config is changed

- debian/copyright
- plugins/mock/translations/de_DE.ts
- plugins/mock/translations/en_US.ts
> Fix copyright

- libguh-core/awsconnector.cpp
- libguh-core/awsconnector.h
- libguh-core/janusconnector.cpp
- libguh-core/jsonrpc/jsonrpcserver.cpp
Some fixes for the remote connection
> Remote connection fixes

- libguh-core/awsconnector.cpp
hopefully this bypasses the SIGSEGV in the libaws when this happens
> disable the auto reconnect from AWS, use our own logic instead

- libguh-core/janusconnector.cpp
- libguh/network/avahi/qtavahiservice.cpp
- libguh/network/avahi/qtavahiservice_p.h
> Stuff some leaks
